"""empty message

Revision ID: 018951c85f54
Revises: d1ae08453091
Create Date: 2017-08-26 05:54:00.074739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018951c85f54'
down_revision = 'd1ae08453091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resources_username_key', 'resources', type_='unique')
    op.drop_column('resources', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.create_unique_constraint('resources_username_key', 'resources', ['username'])
    # ### end Alembic commands ###
