"""empty message

Revision ID: 138a9baad702
Revises: 018951c85f54
Create Date: 2017-08-26 08:11:36.076630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138a9baad702'
down_revision = '018951c85f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'resources', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='unique')
    op.drop_column('resources', 'uuid')
    # ### end Alembic commands ###
