"""empty message

Revision ID: 247bc31d03eb
Revises: 138a9baad702
Create Date: 2017-10-25 07:14:04.068031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247bc31d03eb'
down_revision = '138a9baad702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resources', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_unique_constraint('_resource_unique', 'resources', ['name', 'type', 'created_by'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_resource_unique', 'resources', type_='unique')
    op.alter_column('resources', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
