"""empty message

Revision ID: d1ae08453091
Revises: 7b93278a7e54
Create Date: 2017-08-26 05:12:53.589320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ChoiceType


# revision identifiers, used by Alembic.
revision = 'd1ae08453091'
down_revision = '7b93278a7e54'
branch_labels = None
depends_on = None
RES_JOB_CONFIG = 'JOB_CONFIG'
TYPES = [
        (RES_JOB_CONFIG, 'job config')
    ]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resources',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('created_by', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('type', ChoiceType(TYPES), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.username'], ),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    # ### end Alembic commands ###
