"""empty message

Revision ID: e1d156b505c7
Revises: 7b1ba3c982bf
Create Date: 2018-06-02 05:19:02.807549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d156b505c7'
down_revision = '7b1ba3c982bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'resources', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='unique')
    # ### end Alembic commands ###
